# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTemplate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_template(self):
    self.driver.get("https://steamdb.info/app/359550/")
    self.driver.set_window_size(928, 872)
    self.driver.find_element(By.CSS_SELECTOR, ".highcharts-button-symbol").click()
    obj = self.driver.find_element(By.CSS_SELECTOR, ".highcharts-menu-item:nth-child(1)").click()
    time.sleep(10)
    print(type(obj))

if __name__ == '__main__':
  testTemplate = TestTemplate()
  testTemplate.setup_method(None)
  testTemplate.test_template()
  testTemplate.teardown_method(None)
